### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by quangdaovu** [pulp-platform/pulp-riscv-gnu-toolchain#1]
The first part of README is:

> ###  Getting the sources
> 
> This repository uses submodules. You need the --recursive option to fetch the submodules automatically
> 
>     $ git clone --recursive https://github.com/riscv/riscv-gnu-toolchain
>    
> Alternatively :
> 
>     $ git clone https://github.com/riscv/riscv-gnu-toolchain
>     $ cd riscv-gnu-toolchain
>     $ git submodule update --init --recursive
    
Should we change  https://github.com/riscv/riscv-gnu-toolchain to https://github.com/pulp-platform/pulp-riscv-gnu-toolchain?

**Comment by haugoug** [comment]
Yes indeed this is better I will update it
