### ISSUE TITLE
where is bin folder?

### ISSUE THREAD

**Issue by ziang87** [pulp-platform/pulp-riscv-gnu-toolchain#17]
Hello,everyone.When I do this step"export PULP_RISCV_GCC_TOOLCHAIN=<path to the folder containing the bin folder of the toolchain>".
I can't found bin folder in toolchain,please help!

**Comment by bluewww** [comment]
When you install the toolchain at the a certain location, say `YOUR_PATH`, then you need to point `PULP_RISCV_GCC_TOOLCHAIN` to said path.
