### ISSUE TITLE
Compile application for Ariane

### ISSUE THREAD

**Issue by AnouarNechi** [pulp-platform/pulp-riscv-gnu-toolchain#19]
Hello
the new toolchain is a little bit confusing sorry.
If I want to compile c code to run with on Ariane core knowing that I might use floaiting point in the code. which option should I use to build the toolchain. is this ok:
`./configure --prefix=/opt/riscv --with-arch=rv32imc --with-cmodel=medlow --enable-multilib
make`
or I should use:
`./configure --prefix=/opt/riscv --with-arch=rv64g --with-cmodel=medlow --enable-multilib`

Thank you

**Comment by bluewww** [comment]
You should look at the riscv-manual. There is a section that describes what those extensions mean. For ariane you probably want `rv64gc`.
