### ISSUE TITLE
Making hardware loop feature optional in the tool chain

### ISSUE THREAD

**Issue by Silabs-ArjanB** [pulp-platform/pulp-riscv-gnu-toolchain#23]
Hi PULP team,

In the CV32E40P (aka RI5CY) the 'hardware loop' feature (related to the lpstart0, lpend0, lpcount0, lpstart1, lpend1, lpcount1 CSRs) will still be supported, but it has been decided to make it an optional feature, i.e. based on a top level RTL parameter.  (FYI: The parameter discussion for CV32E40P is summarized in this document: https://github.com/openhwgroup/core-v-docs/blob/master/cores/cv32e40p/CV32E40P_and%20CV32E40_Features_Parameters.pdf)

Soon we expect to include this parameterization in the RTL (https://github.com/openhwgroup/cv32e40p/pull/327).

Could you please make sure that the hardware loop feature becomes an optional part of the tool chain as well (controllable from the command line)? Reason is that users who use a CV32E40P with PULP_HWLP=0 would experience illegal instructions otherwise (if their compiled code would still contain hardware loop based constructs).

Best regards,
Arjan

**Comment by bluewww** [comment]
Use `-mnohwloop`
