### ISSUE TITLE
Error while installing gnu toolchain

### ISSUE THREAD

**Issue by Prarthi1703** [pulp-platform/pulp-riscv-gnu-toolchain#28]
./configure --prefix=/opt/riscv
make linux

![image](https://user-images.githubusercontent.com/70278960/94401428-387f9f00-0188-11eb-8b22-d99f5eff9fe3.p
![gnu_toolchain_error](https://user-images.githubusercontent.com/70278960/94401588-77155980-0188-11eb-9134-afca8fe5c08a.png)
ng)

**Comment by Prarthi1703** [comment]
I was running above command and i am getting error.

**Comment by bluewww** [comment]
`make linux` is not supported with this toolchain. You need to build using newlib.
