### ISSUE TITLE
Whille compiling hello-world example facing issue

### ISSUE THREAD

**Issue by Prarthi1703** [pulp-platform/pulp-riscv-gnu-toolchain#29]
I was trying to run hello-world example, but facing issue

1. Directory path : core-v-verif-master/cv32/sim/core
2. command line : make questa-hell
<img width="871" alt="hello_world_error" src="https://user-images.githubusercontent.com/70278960/94672913-93092e80-0333-11eb-872f-f5077dcabc54.PNG">
o-world

**Comment by bluewww** [comment]
This is a buggy makefile. You should post an issue to the core-v-verif repository.
