### ISSUE TITLE
facing error in gcc toolchain

### ISSUE THREAD

**Issue by Prarthi1703** [pulp-platform/pulp-riscv-gnu-toolchain#30]
I was running below command to genearte hex file, but its shiw error(command not found
<img width="872" alt="command_error" src="https://user-images.githubusercontent.com/70278960/94673579-918c3600-0334-11eb-8ebb-540837ad0cc5.PNG">
)

**command:**
riscv64-unknown-elf-gcc -Ofast -mabi=lp64 -march=rv64i -o hello-world.o hello-world.c

**Comment by bluewww** [comment]
You need to put the `riscv32-unknown-elf-gcc` command in your path
