### ISSUE TITLE
Makefile:524: *** missing separator.  Stop.

### ISSUE THREAD

**Issue by jackyfaster** [pulp-platform/pulp-riscv-gnu-toolchain#35]
Hi, thanks for your job, 
i encountered a error when i ran"make" after "./configure --prefix=/opt/riscv --with-arch=rv32imc --with-cmodel=medlow --enable-multilib" . The error snippet is shown below:
______________________________________________________________________________________________________________
 make -C build-binutils-newlib
make[1]: Entering directory `/root/risc-v/pulp-riscv-gnu-toolchain/build-binutils-newlib'
Makefile:524: *** missing separator.  Stop.
make[1]: Leaving directory `/root/risc-v/pulp-riscv-gnu-toolchain/build-binutils-newlib'
make: *** [stamps/build-binutils-newlib] Error 2
_______________________________________________________________________________________________________________
I've tested it on Ubuntu and centos. 
I would appreciate it if you could give me some help.

**Comment by ryanjtr** [comment]
how can you solve this problem sir

**Comment by jackyfaster** [comment]
I'm sorry, I've been out of this job for a long time, and I can't bring this project back.
