### ISSUE TITLE
build failed when compile gdb - python.c, logs below.

### ISSUE THREAD

**Issue by Moore123** [pulp-platform/pulp-riscv-gnu-toolchain#40]
[ ubuntu-22.04.2LTS  gcc-11.3.0(default) ]
-git clone https://github.com/pulp-platform/pulp-riscv-gnu-toolchain
-cd pulp-riscv-gnu-toolchain/
-git submodule update --init --recursive 
-./configure --prefix=/opt/pupl_riscv --enable-multilib
-make linux
=== compile log :

/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/btrace.h:84:1: note: in expansion of macro ‘DEF_VEC_O’
   84 | DEF_VEC_O (btrace_insn_s);
      | ^~~~~~~~~
In file included from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target.h:74,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/progspace.h:24,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:26:
/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/btrace.h:67:8: note: ‘btrace_insn_s’ {aka ‘struct btrace_insn’} declared here
   67 | struct btrace_insn
      |        ^~~~~~~~~~~
/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c: In function ‘void _initialize_python()’:
/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:1739:22: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]
 1739 |   PyEval_InitThreads ();
      |   ~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/python3.10/Python.h:130,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python-internal.h:94,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:94:
/usr/include/python3.10/ceval.h:122:37: note: declared here
  122 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
      |                                     ^~~~~~~~~~~~~~~~~~
/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:1744:26: error: too few arguments to function ‘int _PyImport_FixupBuiltin(PyObject*, const char*, PyObject*)’
 1744 |   _PyImport_FixupBuiltin (gdb_module, "_gdb");
      |   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.10/import.h:91,
                 from /usr/include/python3.10/Python.h:134,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python-internal.h:94,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:94:
/usr/include/python3.10/cpython/import.h:19:17: note: declared here
   19 | PyAPI_FUNC(int) _PyImport_FixupBuiltin(
      |                 ^~~~~~~~~~~~~~~~~~~~~~
/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:1845:22: warning: ‘void PyEval_ReleaseLock()’ is deprecated [-Wdeprecated-declarations]
 1845 |   PyEval_ReleaseLock ();
      |   ~~~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/python3.10/Python.h:130,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python-internal.h:94,
                 from /opt/Riscv/snitch/pulp-riscv-gnu-toolchain/riscv-binutils-gdb/gdb/python/python.c:94:
/usr/include/python3.10/ceval.h:128:37: note: declared here
  128 | Py_DEPRECATED(3.2) PyAPI_FUNC(void) PyEval_ReleaseLock(void);
      |                                     ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:1891: python.o] Error 1
make[3]: Leaving directory '/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/build-binutils-linux/gdb'
make[2]: *** [Makefile:10456: all-gdb] Error 2
make[2]: Leaving directory '/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/build-binutils-linux'
make[1]: *** [Makefile:851: all] Error 2
make[1]: Leaving directory '/opt/Riscv/snitch/pulp-riscv-gnu-toolchain/build-binutils-linux'
make: *** [Makefile:91: stamps/build-binutils-linux] Error 2

**Comment by ashuthosh-mr** [comment]
Hey how did you solve this?
